# Generated by Django 5.1.7 on 2025-04-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nome_completo',
            field=models.CharField(default='Silas de Almeida Andrade', max_length=255),
            preserve_default=False,
        ),
    ]
