# Generated by Django 5.1.7 on 2025-04-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='is_moderator',
            new_name='moderador',
        ),
    ]
