# Generated by Django 5.1.7 on 2025-04-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_aluno_nome_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(default='20241CSI13I0008', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
