# Generated by Django 5.2 on 2025-04-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='nome',
            field=models.CharField(max_length=10),
        ),
    ]
