# Generated by Django 5.2 on 2025-04-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_material_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceitar_automaticamente', models.BooleanField(default=False)),
                ('bloquear_emprestimos', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='nome',
            field=models.CharField(max_length=20),
        ),
    ]
