# Generated by Django 5.2 on 2025-04-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_usuario_cargo_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimomaterial',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aceito'), ('D', 'Devolvido')], default='P', max_length=1),
        ),
    ]
