# Generated by Django 5.1.7 on 2025-04-25 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderator', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prevista', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data_devolvida', models.DateTimeField()),
                ('devolvido', models.BooleanField(default=False)),
                ('devolução_confirmada', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.aluno')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moderator.material')),
            ],
        ),
    ]
