# Generated by Django 5.1.7 on 2025-05-01 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='quem_aprovou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aprovou_o_pedido', to='accounts.aluno'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aluno', to='accounts.aluno'),
        ),
    ]
