# Generated by Django 5.1.7 on 2025-04-24 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='updated',
            new_name='Data_devolvida',
        ),
    ]
