# Generated by Django 5.1.7 on 2025-04-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolvida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
