# Generated by Django 5.1.7 on 2025-04-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_alter_emprestimo_data_devolvida'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
