# Generated by Django 5.1.7 on 2025-04-25 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_rename_updated_emprestimo_data_devolvida'),
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.material'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
