# Generated by Django 5.1.7 on 2025-04-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_alter_emprestimo_material_delete_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
