# Generated by Django 5.1.7 on 2025-04-25 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0004_alter_emprestimo_created'),
        ('moderator', '0001_initial'),
        ('usuarios', '0002_rename_is_moderator_aluno_moderador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='Data_devolvida',
            new_name='data_devolvida',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='devolução_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.aluno'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moderator.material'),
        ),
    ]
