# Generated by Django 5.1.7 on 2025-04-27 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('quantidade_total', models.PositiveIntegerField(default=0)),
                ('quantidade_disponivel', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('data_prevista', models.DateTimeField()),
                ('pendência', models.BooleanField(default=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.aluno')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.material')),
            ],
            options={
                'ordering': ['-criado'],
            },
        ),
    ]
