# Generated by Django 5.1.7 on 2025-04-25 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
        ('usuarios', '0002_rename_is_moderator_aluno_moderador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('data_prevista', models.DateTimeField()),
                ('pendência', models.BooleanField(default=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.material')),
            ],
        ),
    ]
