# Generated by Django 5.1.7 on 2025-04-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='quantidade',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
